---
- hosts: all
  tags: always
  become: true
  pre_tasks:

    - name: pre-run | update package cache (fedora)
      tags: always
      dnf:
        update_cache: yes
      changed_when: False
      when: ansible_distribution == "Fedora"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_os_family == "Debian"

# - hosts: all
#   tags: base
#   become: true
#   roles:
#     - base

- hosts: servers
  vars:
    ansible_user: tom
  tags: server
  become: true
  roles:
    - server
